import type { Metadata } from "next";
import Sidebar from "./_components/sidebar";
import Navbar from "./_components/navbar";

export const metadata: Metadata = {
  title: "Coffee & Resto | Admin",
  description: "Generated by Coffee & Resto",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="min-h-screen bg-gray-100 md:flex hidden bg-gradient-to-r from-gray-50 to-gray-100">
        <Sidebar />
        <div className="w-full">
          <Navbar />
          {children}
        </div>
      </div>
      <div className="md:hidden">Buka di desktop mode</div>
    </>
  );
}
