import type { Metadata } from "next";
import Sidebar from "./_components/sidebar";
import Navbar from "./_components/navbar";
import { Breadcrumb } from "./_components/bread-crumb";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Coffee & Resto | Admin",
  description: "Generated by Coffee & Resto",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const token = (await cookieStore).get("token")?.value;
  return (
    <>
      <div className="min-h-screen bg-gray-100 md:flex hidden bg-gradient-to-r from-gray-50 to-gray-100 text-black">
        <Sidebar />
        <div className="w-full">
          <Navbar token={token!} />
          <Breadcrumb />
          {children}
        </div>
      </div>
      <div className="md:hidden">Buka di desktop mode</div>
    </>
  );
}
